import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class InstructorCreate {
  @ApiProperty()
  first_name: string;
  @ApiProperty()
  last_name: string;
  @ApiProperty()
  email: string;
  @ApiProperty()
  hire_date: string;
}

export class Instructor {
  @ApiProperty()
  id: number;
  @ApiProperty()
  first_name: string;
  @ApiProperty()
  last_name: string;
  @ApiProperty()
  email: string;
  @ApiProperty()
  hire_date: string;
}
